# Generated by Django 5.0.6 on 2024-05-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='city',
            field=models.CharField(choices=[('Tehran', 'Tehran'), ('Qom', 'Qom'), ('Mashhad', 'Mashhad')], max_length=10, null=True),
        ),
    ]
